COLUMN_MAPPINGS = {
    "saber11_colombia": {
        "ESTU_DEPTO_RESIDE": "region",
        "ESTU_MCPIO_RESIDE": "city",
        "ESTU_GENERO": "gender",
        "PUNT_MATEMATICAS": "math_score",
        "PUNT_LECTURA_CRITICA": "reading_score",
        "PUNT_C_NATURALES": "science_score",
        "PUNT_SOCIALES_CIUDADANAS": "social_score",
        "PUNT_INGLES": "english_score",
        "PUNT_GLOBAL": "global_score",
        "FAMI_ESTRATOVIVIENDA": "socioeconomic_level",
        "COLE_NATURALEZA": "institution_type",
    },
    "enem_brasil": {
        "SG_UF_PROVA": "region",
        "NO_MUNICIPIO_PROVA": "city",
        "TP_SEXO": "gender",
        "NU_NOTA_MT": "math_score",
        "NU_NOTA_LC": "reading_score",
        "NU_NOTA_CN": "science_score",
        "NU_NOTA_CH": "social_score",
        "NU_NOTA_COMP1": "global_score",
        "Q006": "socioeconomic_level",
        "TP_ESCOLA": "institution_type",
    },
    "saberpro_colombia": {
        "estu_consecutivo": "student_id",
        "estu_inst_departamento": "region",
        "estu_prgm_departamento": "region",
        "estu_inst_municipio": "city",
        "estu_prgm_municipio": "city",
        "estu_genero": "gender",
        "estu_nse_individual": "socioeconomic_level",
        "estu_nse_ies": "institution_type",
        "inst_origen": "institution_type",
        "mod_razona_cuantitat_punt": "math_score",
        "mod_lectura_critica_punt": "reading_score",
        "mod_competen_ciudada_punt": "social_score",
        "mod_ingles_punt": "english_score",
        "punt_global": "global_score",
    },
    "pruebasnacionales_dominicana": {
        "Período": "year",
        "Regional": "region",
        "Distrito": "city",
        "Nivel/Modalidad": "institution_type",
        "Español": "reading_score",
        "Matemáticas": "math_score",
        "Sociales": "social_score",
        "Naturales": "science_score",
        "Cantidad de estudiantes": "raw_records_count",
        "Cantidad Femenino": "female_count",
        "Cantidad masculino": "male_count",
    },
    "aprender_argentina": {
        "jurisdiccion": "region",
        "departamento": "city",
        "sector": "institution_type",
        "NSE_nivel_Q1": "socioeconomic_level_q1",
        "NSE_nivel_Q2": "socioeconomic_level_q2",
        "NSE_nivel_Q3": "socioeconomic_level_q3",
        "NSE_nivel_Q4": "socioeconomic_level_q4",
        "NSE_nivel_Q5": "socioeconomic_level_q5",
    },
}


NORMALIZED_COLUMNS = [
    "dataset_id",
    "country",
    "exam",
    "year",
    "student_id",
    "region",
    "city",
    "gender",
    "age",
    "institution_type",
    "socioeconomic_level",
    "math_score",
    "reading_score",
    "science_score",
    "social_score",
    "english_score",
    "global_score",
    "raw_data_json",
]
